exclude: ^(layouts/|static/|themes/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=512"]
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Lint/format: R
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.2
    hooks:
      - id: lintr
        name: Lint R
      - id: style-files
        name: Format R
      - id: no-print-statement
        name: Check print statement

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: ^layouts/partials/anchored_headings.html$
