name: melloc
channels:
  - conda-forge
dependencies:
  - pre-commit=4.6.0
  - r-base=4.3
  - r-dplyr=1.1.4
  - r-ggforce=0.4.2
  - r-ggplot2=3.5.0
  - r-showtext=0.9_7
  - r-knitr=1.44
  - r-rmarkdown=2.25
  - r-curl=5.1.0 # required by `font_add_google()`
