name: build-site
description: Restore renv and build blogdown site to public/ directory

inputs:
  r-version:
    description: R version
    default: "4.2.1"
  hugo-version:
    description: Hugo version to use with blogdown
    default: "0.92.0"

runs:
  using: composite
  steps:
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        cache-environment: true
        cache-downloads: true

    - name: Install Hugo
      shell: bash -el {0}
      run: Rscript -e 'blogdown::install_hugo("${{ inputs.hugo-version }}")'

    - name: Build site
      shell: bash -el {0}
      run: Rscript -e 'blogdown::build_site(build_rmd = TRUE)'
