name: build-site
description: Restore renv and build blogdown site

inputs:
  r-version:
    description: R version
    default: "4.2.1"
  hugo-version:
    description: Hugo version to use with blogdown
    default: "0.92.0"
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ inputs.r-version }}
          
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
      
      - name: Install Hugo
        shell: Rscript {0}
        run: blogdown::install_hugo("{{ inputs.hugo-version }}")
      
      - name: Build site
        shell: Rscript {0}
        run: blogdown::build_site()
