name: Build website

on:
  push:
    branches:
      - feat/*
      
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.1"
          
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
      
      - name: Install Hugo
        shell: Rscript {0}
        run: blogdown::install_hugo("0.92.0")
      
      - name: Build site
        shell: Rscript {0}
        run: blogdown::build_site()
        
      - name: Upload site as artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: public/
          if-no-files-found: error
