name: Build site

on:
  push:
    branches:
      - develop
  
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build site
        uses: .github/actions/build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: melloc
          path: public/
      